### ISSUE TITLE
I have a question CITY_ID and API_KEY?

### ISSUE THREAD

**Issue by elhackerlibre** [Anachron/i3blocks#16]
Hi.
I am using your scripts weather .
I think an excellent script.
but I have a question?
on the line:
id=${CITY_ID}&appid=${API_KEY}
I have to replace my CITY_ID by the city, and API_KEY , which has given me the site http://api.openweathermap.org ?
appreciate your help !

**Comment by Anachron** [comment]
Hey @elhackerlibre it seems like they have changed their website!
Type in your city name here: http://openweathermap.org/
And then on the result page the weather id is in the URL.

Example for London: 
http://openweathermap.org/city/2643743

So 2643743 is the city ID. The API_KEY you get when you register there.

**Comment by elhackerlibre** [comment]
Thanks for taking the time to answer my question!
apology and ask again , but as I understand your explanation, the line is correct ?
id=${3647651}&appid=${b3ecc1d27d26504516947865a7bf1305}
No I did wrong? but the weather i3block , This shows me : **°C**
if I did something wrong please tell me!

**Comment by elhackerlibre** [comment]
thanks for taking the time to answer me!
and understood how it works !
I have to add the API_KEY to escripts , then the ID_CITY instance my city in the blocks
example:
instance = 3647651
if you wrote the script , I congratulate you on this excellent work , it has worked very well so far

**Comment by Anachron** [comment]
I'll close this, please comment if you have further issues.
