### ISSUE TITLE
Why when the weather up to 31 ° C the block changes the color black and white?

### ISSUE THREAD

**Issue by elhackerlibre** [Anachron/i3blocks#18]
Friend have a question ?
Why when the weather up to 31 °C the block changes the color assigned to another color , black and white? . But when the weather turns down the color assigned to it
You know why this problem happens?

**Comment by Anachron** [comment]
Sure, it reaches default emergency value and changes to high priority blocks, which you have colored this way. You can change min_value and max_value accordingly in the script if you want to adjust or disable this feature!
