### ISSUE TITLE
packages count off by one

### ISSUE THREAD

**Issue by dmfay** [Anachron/i3blocks#20]
I'm seeing one fewer package update reported from the blocklet than I am from pacman. Possibly pacman's output format changed since 97bddf9f832ab6d23991a4a5d619129a66b2b0bb such that it's no longer necessary?

```
dian@lamia: ~/.dotfiles [INS] ~/.i3blocks/packages
20
20

dian@lamia: ~/.dotfiles [INS] pacman -Qu | wc -l
21
```

**Comment by Anachron** [comment]
Thanks for your bug report, I'm having some delay but don't worry I'll look into this soon.

**Comment by Anachron** [comment]
Hey @dmfay I believe you are right, I'll send a patch along the way.

**Comment by Anachron** [comment]
Hey mate, I sent a patch along the way!

**Comment by Anachron** [comment]
Closing, if this occurs again, please reopen.
