### ISSUE TITLE
Weather script not working

### ISSUE THREAD

**Issue by bootzin** [Anachron/i3blocks#27]
It simply prints ºC, and not really any useful information

**Comment by Anachron** [comment]
Maybe add your city so it can work? :D

**Comment by bootzin** [comment]
I've added my city (It is the numbers on the url when you ckeck them on openweather, right?) and also created my own API ID, but still nothing

**Comment by Anachron** [comment]
Uh okay, I will check whether the API has changed. Thanks for letting me know!

**Comment by bootzin** [comment]
Ugh, nvm, I fiddled around the bash files and realized you used wget, and I only had curl installed

**Comment by Anachron** [comment]
Alright, all good, thanks for letting me know!
