### ISSUE TITLE
where do I put these?

### ISSUE THREAD

**Issue by NullVoxPopuli** [Anachron/i3blocks#31]
how does i3blocks know where to find these scripts?

**Comment by Anachron** [comment]
You put them in some folder and then set "command" of your `i3blocks.conf` to the location including blockname like here: https://github.com/Anachron/i3blocks/blob/master/i3blocks.conf#L28

**Comment by NullVoxPopuli** [comment]
cool, thanks!

**Comment by Anachron** [comment]
You are welcome!
