### ISSUE TITLE
No weather icon in from of temp

### ISSUE THREAD

**Issue by KaosCreator69** [Anachron/i3blocks#34]
This one is a doozie for me, oddly I have had this work on some of my laptops and others do not.
I feel there is something I do not have installed on some of the laptops.
Maybe it is related to where my font-awesome files are installed, doubt that thou.
I get the temp for my area and I have many keys, lol, many computers using your lovely stuff.
Do you have any thoughts? 
I even went and copied over scripts from working machine to another with same results.

**Comment by Anachron** [comment]
Do the other symbols work? Is the same font-awesome package installed in all of them? 

It's good to check fc-list on every computer too, maybe that gives us a clue.

**Comment by KaosCreator69** [comment]
Same font-awesome package installed on all systems. 
No issues with other font-awesome icons showing up on bar for volume, etc. 
Just this darn weather script, I wonder if has something else to do with processing of it?

I ran in terminal i3blocks -c /home/kaos/.config/i3/i3blocks.conf and looking at the garble in there to see the difference, of coarse urxvt does not display font-awesome.

**Comment by KaosCreator69** [comment]
This is what I see in the one where it does not work, not sure this will help. 

{"":"","full_text":" -8â","short_text":" -8â","color":"#E0E0E0","name":"weather","instance":"5990579","urgent":true}

**Comment by Anachron** [comment]
All terminals are equal? All locals are equal?

**Comment by KaosCreator69** [comment]
DUDE! You NAILED IT!! locale was listing C and others
Did localectl set-locale LANG=en_US.UTF-8 and BAM! YOU DA'MAN!!
Of coarse I exited or rebooted and then logged back in to see it working.

Thanks again for all you do!
