### ISSUE TITLE
firewall block

### ISSUE THREAD

**Issue by sven1** [Anachron/i3blocks#38]
did you edited the sudoers file (sudo visudo) to get "access" to ufw?
my only working "ugly" solution was to add this line
`${USER} ALL=(ALL) NOPASSWD: /bin/ufw status`

but i hate it to give the user some root privileges.. :(
what did you do to get this work?

**Comment by Anachron** [comment]
Yes, that is exactly what I had to do.

I'm using this `pgrep -f ^ufw > /dev/null` nowadays which doesn't need root permissions.
