### ISSUE TITLE
Bad visual behavior in default installation 

### ISSUE THREAD

**Issue by hholst80** [Anachron/i3blocks#39]
The default installation of i3blocks has a serious flaw, that its not keeping the alignment fixed. When Network traffic changes or other textfields changes the position of certain visual elements jumps around. This is very annoying. Certainly not what you would like to have as the default.

**Comment by Anachron** [comment]
That's right, how would you suggest to fix this issue?

**Comment by vKnmnn** [comment]
if you know your the maximum width that your traffic block puts out, and can spare a few pixels of your bar, you can add something to the block config to get rid of that behaviour, like i did for my clock, which kept realining the whole thing every minute at 11 seconds..
The line you need to add to your block in `i3blocks.conf`is `min_width="22:22:22"` and resetting that string to that very long output of your traffic e.g. `"22MB/s"` should get rid of that nuisance.

**Comment by ralphee** [comment]
@vKnmnn epic will test in the morning... :sunglasses:

working like a charm

**Comment by vKnmnn** [comment]
Nice. As a side note:
When you open an issue on someones scripts, made in their own  spare time, you may want to address the issue in a nicer tone than you did here. That way you will more likely receive a positive answer.
Cheers.

PS: you should close the issue, when the problem has been fixed.

**Comment by ralphee** [comment]
@vKnmnn chief...i didnt open the issue ...nonetheless it was driving my ocd into overdrive so thxs for the tip...greatly appreciated..

**Comment by vKnmnn** [comment]
My apologies to you then, @ralpheee88, I was not paying attention to the names. Have a nice one

**Comment by ralphee** [comment]
@vKnmnn chief ...can you pls confirm with the minimum width for the bandwidth block the auto hide feature does not work when there is no connection?

**Comment by vKnmnn** [comment]
sorry, what do you want to know?
i just enabled the bandwidth block, `instance=down`, `min_width="______"` and disconnected from wifi. the block stays where it is and the min_width setting is still respected. what behavior do you expect?

**Comment by ralphee** [comment]
@vKnmnn thxs for testing!!! I could be mistaken but if there is no internet connection and min width is not set i believe there should be an auto hide function...(hope that makes sense)

(the minimum width makes the notifications persistent)

**Comment by vKnmnn** [comment]
Do you want the block to disappear, when you are disconnected from wifi?
Or do you want the block to disappear, when it shows 0b? (which might happen, even when you are connected)
The min_width setting has nothing to do with this.

**Comment by ralphee** [comment]
@vKnmnn yeah ideally i would like the block to disappear when there is inactivity after a few seconds

**Comment by vKnmnn** [comment]
that would probably take some rewriting. since i'm not using the bandwith block, i won't do it for you, but scripting is not that hard, so you could learn it yourself. 
realistically, the throughput of a network interface doesn't stay at 0 for long, at any time, anyways. You should be able to see that in your block.
Making the block disappear, on disconnect is rather easy. would you like help with that?

**Comment by vKnmnn** [comment]
you see, the block script is run every second, so it is hard to keep track on how long throughput has been zero

**Comment by ralphee** [comment]
@vKnmnn thxs for the insight! making the block disappear on disconnect would be a good compromise. If and whenever you have time your help would be greatly appreciated!

**Comment by vKnmnn** [comment]
alright. so i will find a command which output tells me, that wifi is disconnected. i'll check that variable in the beginning of the script, and just let the block exit without giving any output. that way, the block should disappear.

are you using wireless? wireless only or do you use both wifi and LAN
?

**Comment by ralphee** [comment]
@vKnmnn cant thank you enough...ironically i like to have a clean status bar

**Comment by vKnmnn** [comment]
which device are you running the blocks on? wireless, wired or both? i need to know which ones. they go by names like wlp2s0 (wireless) enp0s3 (wired).
(find out with `ip link`)

**Comment by ralphee** [comment]
@vknmnn wlp4s0 & enp0s31f6

**Comment by vKnmnn** [comment]
alright. just add this right after the first if-clause.
```
if  [[ "${INTERFACE}" = "" ]]; then
        exit
fi
```
the first if-clause checks, whether you can reach googles dns server 8.8.8.8.
If you can't, the variable INTERFACE will be an empty string. 

in this if clause, we check, if the string really is empty, and if it is, we just kill the script, so it will not output anything else.
have fun with it.

**Comment by ralphee** [comment]
Superstar...will have a crack and let you know...

really small glitch... when not connected it shows one output/input of the block (not sure which one)

![imgur-2017_09_15-08 55 04](https://user-images.githubusercontent.com/8269794/30470274-51eca626-99f4-11e7-9780-3bec15e72681.png)

My apologies ...i had a typo...its working beautifully...Thxs!!!

**Comment by vKnmnn** [comment]
gonna close this
