### ISSUE TITLE
How to add them?

### ISSUE THREAD

**Issue by 256k** [Anachron/i3blocks#43]
Hey srry if this is a noob question but i am a noob indeed. was curious to know how to add these scripts,

I tried to cp  them into usr/share/i3blocks where i saw was the default ones but it gave me permission denied....

Some clarification would be great thanks.

**Comment by zeljkobekcic** [comment]
You dont need to clone/copy them into /usr/share/i3blocks, I have cloned mine into ~/.config/i3blocks.
But this depends on what you want to do with these blocklets/scripts and this does not answer your question. You need to copy them with 'sudo', like 'sudo do-something'. If you really want/need to copy them into this directory is another question.

**Comment by vKnmnn** [comment]
put them anywhere you want. i would suggest putting them in `$HOME/.config/i3blocks/blocks` but it doesnt really matter. Just give the absolute path (beginning with `/` in the `command=...` section of the blocks.
