### ISSUE TITLE
merging with vivien's i3blocks-contrib

### ISSUE THREAD

**Issue by vKnmnn** [Anachron/i3blocks#46]
Hey @Anachron 
What do you think about merging your blocks with the ones in vivien's repo. That would combine the two biggest collections of blocks into one source. I'm sure many people could benefit from that.
I would even work on it, provide screenshots, write readme's. 
You might wan't to put some annotaion to your blocks, to link back to you or something.
If you don't care about it at all, i will PR them just as they are and maintain them as well

**Comment by ralphee** [comment]
Pretty much what I did... Git cloned both repos... 1+ to combine...

**Comment by Anachron** [comment]
Hey @vKnmnn @ralpheeee88 good idea, I will open an issue on vivien.

**Comment by Anachron** [comment]
Sadly this didn't went too well, closing it for now.

https://github.com/vivien/i3blocks-contrib/issues/169
