### ISSUE TITLE
feature request scaling governor 

### ISSUE THREAD

**Issue by ralphee** [Anachron/i3blocks#49]
was wondering if its possible to have a block indicating which cpu Scaling governor is currently active....

[https://wiki.archlinux.org/index.php/CPU_frequency_scaling#Scaling_governors](url)

**Comment by vKnmnn** [comment]
put this as your command in a block: `cpupower frequency-info | grep "may decide which speed to use" | awk  '{ print $3 }' | tr -d \"`

**Comment by vKnmnn** [comment]
@ralphee, if this has solved you request, please consider closing this issue.
