### ISSUE TITLE
weather script: Faulty grep ranges

### ISSUE THREAD

**Issue by simonszu** [Anachron/i3blocks#50]
Hi,

i didn't get the weather block to work, so i tried to execute it manually. This resulted in the following output:

```
$ ./weather.sh                                                                                                                                                                                    
grep: Das Ende des angegebenen Intervalls ist nicht gültig
 20℃
 20℃

````

The grep error roughly translates to "The end of the given interval is invalid" or something. Is this the intended behavior?

**Comment by Anachron** [comment]
Nope, weird. I'll see if I can replicate.

**Comment by vKnmnn** [comment]
it's possible that you have a different flavor of grep installed. are you on a mac possibly, or bsd or something esoteric?
