### ISSUE TITLE
Showing symbols instead of Icons

### ISSUE THREAD

**Issue by abelncm** [Anachron/i3blocks#51]
Icons are not showing, instead there are character symbols.
How do I get it to work? Is there a specific font that I have to use in i3 config file?

**Comment by Anachron** [comment]
Yes font awesome! Any recent version should work:

**Comment by vKnmnn** [comment]
You just have to have installed the fonts. you do not need to add them to your config.
good fonts are font awesome and symbola.
closing this due to age.
