### ISSUE TITLE
help with webcam script

### ISSUE THREAD

**Issue by batmanm0b1E** [Anachron/i3blocks#52]
I'm trying to use your webcam script on i3blocks, nothing is showing up if you can help me out Thank you

**Comment by batmanm0b1E** [comment]
Still need help please?

**Comment by Anachron** [comment]
I'm sorry I forgot about this.

I am guessing your webcam device is not /dev/video0.

https://github.com/Anachron/i3blocks/blob/master/blocks/webcam

You will have to replace it with your appropiate device path.

**Comment by yuceltoluyag** [comment]
` line 12: syntax error near unexpected token `else'
`
