### ISSUE TITLE
Weird block space characters after ttf-font-awesome characters

### ISSUE THREAD

**Issue by YodaEmbedding** [Anachron/i3blocks#53]
It looks like spaces (0020) are being poorly displayed:

![i3blocks](https://i.imgur.com/pe5x3Ic.jpg)

I'm guessing this comes with the recent update to `ttf-font-awesome`. The reason I raised this issue here is because vim and Sublime Text seem to be displaying the font correctly:

![vim](https://i.imgur.com/gAzXXi8.jpg)
![subl](https://i.imgur.com/wAjiVmv.jpg)

i3 config:

```
bar {
    status_command i3blocks
    font pango:FontAwesome 10
}
```

i3blocks config:

```
[disk]
label=
interval=30
```

(Notice that there is no space explicitly defined within `label=`.)

**Comment by 0x6C38** [comment]
Same issue after update

**Comment by Anachron** [comment]
That's weird, does "fp-cache -f" do any change? (run as admin)

**Comment by YodaEmbedding** [comment]
`sudo fc-cache -f` doesn't seem to have any effect.

**Comment by Anachron** [comment]
The weird thing is I cannot reproduce this on `Void Linux` (glibc).
If you specify two fonts (fallback font like "Ubuntu Mono, Source Code Pro" or alike), does the problem still appear?

**Comment by YodaEmbedding** [comment]
I tried the following `i3config` configurations: 

```
font pango:FontAwesome, pango:Roboto Mono 10
font pango:Roboto Mono, pango:FontAwesome 10
```

But none of them fixed this issue. I am using the [`i3-wm`](https://www.archlinux.org/packages/community/x86_64/i3-wm/) and [`i3blocks`](https://www.archlinux.org/packages/community/x86_64/i3blocks/) packages for Arch.

**Comment by chrisdruta** [comment]
Find a solution yet? I'm running i3-gaps with i3blocks on arch as well.

**Comment by Anachron** [comment]
I saw issues like this on the font-awesome repo issues. Can you report upstream?

**Comment by pree** [comment]
Found a Topic on the Archlinux Forums about this: https://bbs.archlinux.org/viewtopic.php?id=233098

Uninstalling `ttf-font-awesome` and installing `otf-font-awesome` worked for me.

**Comment by YodaEmbedding** [comment]
This issue can be closed. (Though, I suppose for now that it might be better to leave open for visibility.)

Quoting [@ael](https://bugs.archlinux.org/task/56899#comment165101):

> The bug is actually related to Pango. In fact i3wm use Pango to render text. The problem is that Pango does not correctly fallback to another font to render the space character U+0020 [1][2]. The new ttf Font Awesome 5 fonts do not provide anymore a space character, thus using a space after a proper Font Awesome char trigger the Pango bad behavior.
> 
> If you have ttf-fontawesome-5 installed you can reproduce the problem with:
> pango-view -t ' A ' --font "pango:Font Awesome 5 Free"
> 
> You will see that the space after the bike (U+F206) is not correctly rendered while the space after the A letter is properly rendered.
> 
> [1] https://bugzilla.gnome.org/show_bug.cgi?id=775202
> [2] https://bugzilla.gnome.org/show_bug.cgi?id=780068
>
