### ISSUE TITLE
Report : weather script missing out "thunderstorm"

### ISSUE THREAD

**Issue by thyeun** [Anachron/i3blocks#54]
i'm new to this, so anyone that maintain the script, hope you can add "thunderstorm" into the script, so that it will benefit to others users that need it.

add this 
```
  elif [[ "${WEATHER_MAIN}" = *Thunderstorm* ]]; then
  echo "${ICON_STORM} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
  echo "${ICON_STORM} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
  echo ""
```

**Comment by vKnmnn** [comment]
closing this, because ghost has added the lines in the weather block
