### ISSUE TITLE
Firewall block

### ISSUE THREAD

**Issue by iAmG-r00t** [Anachron/i3blocks#58]
Hey the firewall status can't be seen, how do I fix that I am new at i3blocks, but I know ufw requires root permission. I have tried to understand the firewall scritp in the blocks directory but I am lost kindly assist.

**Comment by vKnmnn** [comment]
Hi. If you had searched the issues for the word firewall you would have found #38  ;)

There's a hint on how to solve it there. 
Let me know if you need more help.

**Comment by iAmG-r00t** [comment]
Hey I did see that, you told him that nowadays you use pgrep -f ^ufw > /dev/null, and I have placed that in the command section but still it doesn't work kindly assist

**Comment by iAmG-r00t** [comment]
Kindly give me some other clue that won't make me edit my sudoers file

**Comment by vKnmnn** [comment]
take a look at commit b6e5805

**Comment by iAmG-r00t** [comment]
Okay thanks for that, I would request you to add this on the readme for the people who will be interested to make it work without having to make the system more insecure. To add this line to the '/etc/sudoers' file it will allow the command sudo ufw status to be ran without any password on that host and by that specific user only.

# Enable this command to run without sudo password
$USER $HOST = (root) NOPASSWD: /usr/sbin/ufw

It works really well, thanks alot.
